# Generated by Django 3.0 on 2020-05-08 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mynews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategoriya nomi *')),
                ('slug', models.SlugField(blank=True, max_length=25, verbose_name='Kalit so`z *')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='SubKategoriya nomi *')),
                ('slug', models.SlugField(blank=True, max_length=25, verbose_name='Kalit so`z *')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynews.Category', verbose_name='Kategoriya *')),
            ],
            options={
                'verbose_name': 'SubKategoriya',
                'verbose_name_plural': 'SubKategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Yanglik nomi *')),
                ('slug', models.SlugField(max_length=25, verbose_name='Kalit so`z *')),
                ('description', models.TextField(max_length=1550, verbose_name='Yanglik matni *')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name="Ko'rildi")),
                ('popular', models.BooleanField(default=False, verbose_name='Populyar')),
                ('shared', models.PositiveIntegerField(blank=True, default=0, verbose_name='Ulashildi')),
                ('info', models.CharField(blank=True, max_length=5, verbose_name='Qisqa ma`lumot masalan yangi,new,ko`p ko`rildi kabi')),
                ('image_one', models.ImageField(blank=True, upload_to=mynews.models.image_folder, verbose_name='Foto bosh saxifaga N:1 950x830px')),
                ('image_two', models.ImageField(blank=True, upload_to=mynews.models.image_folder, verbose_name='Foto bosh saxifaga N:2 670x390')),
                ('image_there', models.ImageField(upload_to=mynews.models.image_folder, verbose_name='Foto boshqalar N:3 700x600*')),
                ('avialable', models.BooleanField(default=True, verbose_name='Status')),
                ('reg_data', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated', models.DateField(auto_now=True)),
                ('added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shdi")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynews.Category', verbose_name='Kategoriya *')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mynews.SubCategory', verbose_name='SubKategoriya ')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
