# Generated by Django 3.0 on 2020-05-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mynews.SubCategory', verbose_name='SubKategoriya '),
        ),
    ]
