# Generated by Django 3.0 on 2020-05-09 04:41

from django.db import migrations, models
import mynews.models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_auto_20200508_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slider',
            field=models.BooleanField(default=False, verbose_name='Sliderga'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_one',
            field=models.ImageField(blank=True, upload_to=mynews.models.image_folder, verbose_name='Foto bosh saxifaga N:1 850x630px'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Yangilandi'),
        ),
    ]
