# Generated by Django 3.0 on 2020-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0004_auto_20200509_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Muxokamalar soni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='shared',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ulashishlar soni'),
        ),
    ]
